### ISSUE TITLE
Only Depth Estimation portion of network

### ISSUE THREAD

**Issue by asamra18** [isarandi/metrabs#24]
Hello,
First I would like to say great work. Testing it on some custom images the model performs quite nicely and has some features I didn't think I would end up using. Further, I have a question in regards to the depth estimation only. I currently am building a model and am using YOLO v5 as the detector, and Open-Pose as the pose estimator, and was wondering if its possible to extract only the depth of the keypoints. Essentially, I was wondering if its possible to extract only the depth estimation portion of the network and feed it the keypoints I obtain from OpenPose and return the depths of these key points. 

Thank you,
Anand

**Comment by isarandi** [comment]
Hi Anand! If I understand correctly, you'd like to feed the output of OpenPose (2D joints) into this network and get only the Z coordinate for each joint. Unfortunately, this is not possible with this network due to the way it was trained. However, it is certainly an interesting and valid use case that I'll keep in mind for the future.

**Comment by asamra18** [comment]
Hello,
Thank you for the reply, I appreciate the clarification.
