### ISSUE TITLE
Results with 3DPW train

### ISSUE THREAD

**Issue by raulTrial** [isarandi/metrabs#48]
Hi, Thanks for the nice project. Is there by any chance you have results/model trained on 3DPW too?

**Comment by isarandi** [comment]
Hi, thanks for your interest! I haven't used 3DPW for training. I think that kind of protocol is now discouraged by the 3DPW authors and the whole dataset should be used for testing.

**Comment by raulTrial** [comment]
Hi, yes that makes complete sense. The whole HPE is riddled with models trained on different datasets and different evaluation techniques(for ex: full 3dpw test shows better results than only test set); so its a bit hard to gauge what actually makes a method work. But nonetheless you have a very nice approach.

**Comment by raulTrial** [comment]
Hi @isarandi, sorry but one more question. Do you have the MPJPE/PA-MPJPE for 3DHP and MuPoTS for the current models? the paper has it but I guess, it was not trained on the large dataset for them.

**Comment by isarandi** [comment]
I have some new, better models trained on even more datasets. The corresponding paper is already accepted for WACV'23, I'm finalizing the camera ready version.

I can share any type of eval results you need. As there are so many different datasets, eval protocols, eval measures, subsets (like actions), model configurations (backbone, striding, test-time augmentation) etc. it's hard to provide all the numbers, so that page here on Github is just a selection...

**Comment by raulTrial** [comment]
Congratulations!!! I'll wait for your paper.
