### ISSUE TITLE
How can I test some images with different resolution?

### ISSUE THREAD

**Issue by linjing7** [isarandi/metrabs#58]
@isarandi Hi, I want to test some images with `estimate_poses_batched()` function. However, the image sizes of the images are not the same. Thus, there would be something wrong with `tf.data.Dataset.from_generator`. I try to resize and pad the images into the same resolution in the generator, but the `pred['poses3d']` would be different from the original one. When I resize and crop the images, do I need to modify `pred['poses3d'] `?

**Comment by isarandi** [comment]
Hi, thanks for the interest! The simplest way would be to not use batching, ie to use the single-image functions (similar to a batch size of 1). If the size differences are small, you can indeed do padding, but make sure to specify the correct intrinsic matrices.

**Comment by linjing7** [comment]
Hi, thanks for your reply. I want to test some in-the-wild images, so I do not know the exact intrinsic. In this case, when I resize and crop the images, what should I do to get the correct result?

**Comment by isarandi** [comment]
Depends on the situation. The batched interface is mostly intended for processing videos and images from datasets with fixed resolutions.

If you have different resolutions, then _the recommended simple way is to just use a batch size of 1_, so each image can have arbitrary size.

Else, you need to decide how exactly you want to crop/pad/resize images. Eg. you can resize all to a fixed height, or the max height in the current batch etc. Then you can symmetrically pad black pixels to the left and right of each image, so you make each image equal sized.  Padding symmetrically is simpler, because if the principal point was centered, it will also remain centered after symmetric padding, so the intrinsics don't need to be changed much (since you don't know the intrinsics, you might take a guess for the original image and multiply by the zoom level you needed to apply when resizing).

Then you can feed this batch to the model. It's conceptually fairly simple but there are many variations on the exact steps depending on how much the image sizes vary, the image aspect ratios, etc. I can't provide code for this unfortunately, it's quite involved to satisfy every use case while also keeping it simple. If it sounds too daunting, just go with batch size 1, that's quite simple.

**Comment by linjing7** [comment]
@isarandi Okay, thanks for your detailed answer! I'll have a try.
